# Numpy
Es un paquete fundamental para la computación científica en Python y manejo de arrays numéricos multi-dimensionales.
Importamos el paquete: `import numpy as np`

En el núcleo de NumPy está el ndarray, donde «nd» es por n-dimensional. Un ndarray es un array multidimensional de elementos del mismo tipo.
El cómputo es casi 12 veces más rápido utilizando ndarray frente a listas clásicas.

## Tipos de datos
NumPy maneja gran cantidad de tipos de datos. A diferencia de los tipos de datos numéricos en Python que no establecen un tamaño de bytes de almacenamiento, aquí sí hay una diferencia clara.
Algunos de los tipos de datos numéricos en NumPy se presentan en la siguiente tabla:

|dtype | Descripción | Rango|
|---|---|---|
|np.int32 | Integer | De -2147483648 a 2147483647|
|np.int64 | Integer | De -9223372036854775808 a 9223372036854775807
|np.uint32 | Unsigned integer| De 0 a 4294967295|
|np.uint64 | Unsigned integer| De 0 a 18446744073709551615|
|np.float32 | Float | De -3.4028235e+38 a 3.4028235e+38|
|np.float64 | Float | De -1.7976931348623157e+308 a 1.7976931348623157e+308|

**Truco:** NumPy entiende por defecto que int hace referencia a np.int64 y que float hace referencia a np.float64. Son «alias» bastante utilizados.

### Convertir a otro tipo
Se logra esto mediante el uso de `astype`.
Además existe la posibilidad de convertir a una lista cualquier ndarray mediante el método `tolist()`.

In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
print(x) # [1 2 3 4 5]

print(type(x)) # <class 'numpy.ndarray'>
print(x.ndim) # Dimesion: 1
print(x.size) # Tamaño: 5
print(x.shape) # Forma: (5, )
print(x.dtype) # Tipo de sus elementos: int64

# Espeficicando el tipo de dato
y = np.array([10, 20, 30, 40, 50], dtype='int32')
print(y) # [10 20 30 40 50]
print(y.dtype) # int32

# Convertiendo un tipo de dato a otro: int a float con astype
f = y.astype(float)
print(f.dtype) # float64

# Convertir ndarray a lista : tolist()
lista = f.tolist()
print(type(lista)) # <class 'list'>

## Matrices
Una matriz no es más que un array bidimensional. Como ya se ha comentado, NumPy provee ndarray que se comporta como un array multidimensional con lo que podríamos crear una matriz sin mayor problema.



In [ ]:
matriz = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12] ])

print(matriz) # [[ 1  2  3]
            # [ 4  5  6]
            # [ 7  8  9]
            # [10 11 12]]

print(matriz.ndim) # 2
print(matriz.size) # 12
print(matriz.shape) # (4, 3) -> 4 filas x 3 columnas
print(matriz.dtype) # int64

array1 = np.array([88, 23, 39, 41])
array2 = np.array([[76.4 , 21.7, 38.4], [41.2, 52.8, 68.9]])
array3 = np.array([[12], [4], [9], [8]])

print(array1) # [88 23 39 41]

print(array2) # [[76.4 21.7 38.4]
            # [41.2 52.8 68.9]]

print(array3) # [[12]
            # [ 4]
            # [ 9]
            # [ 8]]

## Cambiando forma
Se puede cambiar la forma del array con la función `np.reshape()`

## Almacenando arrays
Es posible que nos interese almacenar (de forma persistente) los arrays que hemos ido creando. Para ello NumPy nos provee, al menos, de dos mecanismos:
1. Almacenamiento en formato binario propio: Mediante el método `save()` podemos
guardar la estructura de datos en ficheros .npy.
2. Almacenamiento en formato de texto plano: NumPy proporciona el método `savetxt()` con el que podremos volcar la estructura de datos a un fichero de
texto csv.

### Desempaquetar valores
Es posible cargar un array desempaquetando sus valores a través del parámetro `unpack`.

In [ ]:
numeros = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(np.reshape(numeros, (3, 4))) # 3 filas x 4 columnas

# Si sólo queremos especificar un número determinado de filas o columnas,
# podemos dejar la otra dimensión a -1:
print(np.reshape(numeros, (6, -1)))
print(np.reshape(numeros, (-1, 6)))

matriz = np.reshape(numeros, (3, 4))

print()
# Almacenando arrays :
# Forma 1 : Almacenamiento en formato binario propio -> save()
np.save('my_matrix', matriz)

# Leemos
matriz_cargada_1 = np.load('my_matrix.npy')
print(matriz_cargada_1)

print()
# Forma 2 : Almacenamiento en formato de texto plano -> savetxt()
np.savetxt('my_matrix.csv', matriz, fmt='%d')

# !cat my_matrix.csv

# Leemos
matriz_cargada_2 = np.loadtxt('my_matrix.csv', dtype=int)
print(matriz_cargada_2)

# Desempaquetado
print()
col1, col2, col3, col4 = np.loadtxt('my_matrix.csv', unpack=True, dtype=int)

print(col1)
print(col2)
print(col3)
print(col4)

# Funciones predefinidas para creación de arrays
NumPy ofrece una gran variedad de funciones predefinidas para creación de arrays que nos
permiten simplificar el proceso de construcción de este tipo de estructuras de datos.
1. Ceros: `np.zeros((3, 4))` dtype default float.
    * `np.zeros((3, 4) dtype=int)`

In [ ]:
# Ceros
print(np.zeros((2, 2))) # o dtype=int

print()
# Unos
print(np.ones((2, 2)))

print()
# Mismo valor
print(np.full((2, 2), 7)) # np.full_like()

print()
# Matriz identidad
print(np.eye(2))

print()
# Matriz diagonal
print(np.diag([1, 2]))

print()
# Ejercicio
matriz = np.diag(range(50))
print(matriz)


## Valores enteros equiespaciados
La función que usamos para este propósito es `np.arange() ` cuyo comportamiento es totalmente análogo a la función «built-in» `range()`.

## Valores flotantes equiespaciados
La función que usamos para este propósito es `np.linspace()` cuyo comportamiento es «similar» a `np.arange()` pero para valores flotantes.
Por defecto esta genera 50 elementos.

In [ ]:
# Valores enteros equiespaciados
# Especificando límite superior:
x = np.arange(10)
print(x) # [0 1 2 3 4 5 6 7 8 9]

# Especificando límite superior e inferior:
x = np.arange(5, 10)
print(x) # [5 6 7 8 9]

# Especificando límite superior e inferior y paso:
x = np.arange(1, 10, 2)
print(x) # [1 3 5 7 9]

# Paso flotante
paso_flotante = np.arange(6, 8, 0.3)
print(paso_flotante) # [6.  6.3 6.6 6.9 7.2 7.5 7.8]

# Valores flotantes equiespaciados
# Especificando límite superior e inferior -> default 50 elementos:
x = np.linspace(5, 10)
print(x)

# Especificando límite superior e inferior y total de elementos:
x = np.linspace(6, 60, 10)
print(x) # [ 6. 12. 18. 24. 30. 36. 42. 48. 54. 60.]

# Especificando un intervalo abieto
x = np.linspace(6, 60, 10, endpoint=False)
print(x)

In [ ]:
import numpy as np
# Valores aleatorios enteros
print(np.random.randint(3, 30)) # Escalar

print(np.random.randint(3, 30, size=9)) # Vector

print(np.random.randint(3, 30, size=(3, 3))) # Matriz

# Valores aleatorios flotantes
print(np.random.random(9)) # Entre 0 y 1

print(np.random.uniform(1, 100, size=9)) # [a, b] y tamaño

20
[ 8 15 22 22 13 14 20  4 27]
[[28 23 26]
 [ 6 18  4]
 [26 23 13]]
[0.11011429 0.04179755 0.17256116 0.92436799 0.75451354 0.30920549
 0.8395853  0.63005748 0.50419813]
[15.69373181 84.04718395 78.05935722 76.8565685  14.81303014 26.76340518
 18.95165188 13.54352605 83.11654521]


In [ ]:
# Distribuciones de probabilidad

# Distribución de probabilidad normal: Generar 5 números
# aleatorios con media 0 y desviación estándar 1
print(np.random.normal(0, 1, 5))

print(np.random.choice(['Cara', 'Cruz'], size=10))

[-0.06828072 -0.75243376 -0.30757568  0.50917158 -0.30746695]
['Cruz' 'Cara' 'Cara' 'Cruz' 'Cara' 'Cara' 'Cruz' 'Cara' 'Cara' 'Cruz']


* Una matriz de 20 filas y 5 columnas con valores flotantes equiespaciados en el intervalo
cerrado [1, 10].
* Un array unidimensional con 128 valores aleatorios de una distribución normal 𝜇 = 1, 𝜎 = 2.
* Un array unidimensional con 15 valores aleatorios de una muestra 1, X, 2 donde la
probabilidad de que gane el equipo local es del 50%, la probabilidad de que empaten
es del 30% y la probabilidad de que gane el visitante es del 20%.

In [ ]:
import numpy as np
# Ejercicios
valores = [1, 'X', 2]

# 1
matriz = np.linspace(1, 10, num=6).reshape(2, 3)
print(matriz)

# 2
print(np.random.normal(1, 2, size=6))

# 3
# Definir las probabilidades correspondientes
probabilidades = [0.5, 0.3, 0.2]

# Generar el array unidimensional con 15 valores aleatorios según las probabilidades
resultados = np.random.choice(valores, size=15, p=probabilidades)

print(resultados)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
[2.20121616 2.46777054 1.64165085 1.70667585 0.24253259 0.8823986 ]
['1' '2' '2' 'X' '2' '1' 'X' 'X' 'X' '1' 'X' '2' '1' 'X' 'X']


# Manipulando elementos
## Arrays unidimensionlaes

In [ ]:
import numpy as np

valores = np.array([10, 20, 30, 40, 50])

print(valores[2])
print(valores[4])

# Modificación del arreglo
valores[0] = valores[3] + valores[4]
print(valores)

# Borrando : np.delete() no es destructiva sino que devulve una copia del arreglo
print(np.delete(valores, 0)) # Indice (como escalar)

borrados = np.delete(valores, (2, 3, 4)) # Indices (com tupla)
print(borrados)

# Inserción : ambas funciones no son destructivas sino que devuelven una copia
print(np.append(valores, 200)) # Añade al final
print(np.insert(valores, 0, 1000)) # Añade en la posición especificada
print(np.append(valores, [800, 900, 1500])) # Añadir varios de una vez

## Arrays multidimensionales

In [ ]:
valores = np.arange(1, 13).reshape(3, 4)
print(valores)

# Acceso a elementos
# Individuales
print(valores[0][0]) # 1
print(valores[2][3]) # 2

# Múltiples
print(valores[[0, 2], [1, 2]]) # [ 2, 11]

# Filas o columnas completas
print(valores[2]) # Tercer fila
print(valores[:, 1]) # Segunda columna

# Zonas parciales
print(valores[0:2, 0:2])
print(valores[0:2, [1, 3]])

# Modificando
valores[0,0] = 100
valores[1] = [500, 600, 700, 800]
valores[:, 1] = [2000, 6000, 10000]

print(valores)
print()
# Borrando
print(np.delete(valores, 0, axis=0)) # Borrado primer fila
print(np.delete(valores, (1, 3), axis=1)) # Borrado 2 y 4 columna


In [ ]:
import numpy as np
# Inserción
numeros = np.array([[1, 2], [3, 4]])

# Al final
print(np.append(numeros, [[5, 6]], axis=0))
print(np.append(numeros, [[5], [6]], axis=1))

# Arbitrariamente
print(np.insert(numeros, 0, [0, 0], axis=0))
print(np.insert(numeros, 1, [0, 0], axis=1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[[0 0]
 [1 2]
 [3 4]]
[[1 0 2]
 [3 0 4]]


In [ ]:

# Ejercicio
matriz = np.array([[17, 12, 31], [49, 11, 51], [21, 31, 62], [63, 75, 22]])
print(matriz)

#fila_cuatro = matriz[3]
#print(fila_cuatro)

print()
# Eliminamos la fila 3
matriz = np.delete(matriz, 3, axis=0)
print(matriz)

print()
# Agregamos en forma de columna
matriz = np.append(matriz, [[63], [75], [22]], axis=1)
print(matriz)

print()
# Cambiando de valores la segunda fila
matriz[1] = [49, 49, 49, 63]
print(matriz)

print()
# Cambiando de valores la columna 4
matriz[:,3] = [63, 63, 63]
print(matriz)

## Apilando matrices
Hay veces que nos interesa combinar dos matrices (arrays en general). Una de los mecanismos que nos proporciona NumPy es el apilado.

Dos apilados:
1. Vertical
2. Horizontal

In [ ]:
import numpy as np
a = np.random.randint(1, 100, size=(3, 2)) # 3 Filas x 2 Columnas
b = np.random.randint(1, 100, size=(1, 2)) # 1 Fila x 2 Columnas

print(a)
print(b)
print()

# Apilado vertical : np.vstack((a, b))
print(np.vstack((a, b)))
print()

a = np.random.randint(1, 100, size=(3, 2)) # 3 Filas x 2 Columnas
b = np.random.randint(1, 100, size=(3, 1)) # 3 Fila x 1 Columnas

print(a)
print(b)
print()

# Apilado horizontal : np.hstack((a, b))
print(np.hstack((a, b)))

[[95 98]
 [79 50]
 [ 2 67]]
[[32 94]]

[[95 98]
 [79 50]
 [ 2 67]
 [32 94]]

[[49 83]
 [93 60]
 [ 7  4]]
[[80]
 [58]
 [21]]

[[49 83 80]
 [93 60 58]
 [ 7  4 21]]


## Repitiendo elementos
Existen dos tipos:
1. **Repetición por ejes**: El parámetro de repetición indica el número de veces que repetimos el array completo por cada eje.
2. **Repetición por elementos**: El parámetro de repetición indica el número de veces que repetimos cada elemento del array.

In [ ]:
# Rep. por ejes
valores = np.array([[1, 2], [3, 4], [5, 6]])

print(np.tile(valores, 3)) # x3 en columnas
print()

print(np.tile(valores, (2, 3)))
print()

# Rep. por elementos
print(np.repeat(valores, 2))

print(np.repeat(valores, 2, axis=0)) # # x2 en filas

print(np.repeat(valores, 3, axis=1)) # x3 en columnas

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [5 6 5 6 5 6]]

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [5 6 5 6 5 6]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [5 6 5 6 5 6]]

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2]
 [1 2]
 [3 4]
 [3 4]
 [5 6]
 [5 6]]
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]
 [5 5 5 6 6 6]]


## Acceso por diagonal
Es bastante común acceder a elementos de una matriz (array en general) tomando como referencia su diagonal. Para ello, NumPy nos provee de ciertos mecanismos.

### Extracción de elementos por diagonal
La función `np.diag()` permite acceder a los elementos de un array especificando un parámetro **k** que indica la «distancia» con la diagonal principal.

![Imagen](https://aprendepython.es/_images/numpy-diagonal.png)

---
### Modificación de elementos por diagonal
NumPy también provee un método `np.diag_indices()` que retorna los índices de los elementos de la diagonal principal, con lo que podemos modificar sus valores directamente.

In [ ]:
import numpy as np
# Extracción

matriz = np.array([[73, 86, 90, 20], [96, 55, 15, 48], [38, 63, 96, 95],
[13, 87, 32, 96]])

print(matriz, '\n')

print(np.diag(matriz), '\n') # k = 0

for k in range(1, matriz.shape[0]):
    print(f'k={k}', np.diag(matriz, k=k))

print()

for k in range(1, matriz.shape[0]):
    print(f'k={-k}', np.diag(matriz, k=-k))

# Modificación
di = np.diag_indices(matriz.shape[0])
matriz[di] = 0
print('\n', matriz)

# np.triue_indices : obtiene los índices de los
# elementos superiores de una matriz cuadrada
indices_superiores = np.triu_indices(matriz.shape[0], k=1)
elementos_superiores = matriz[indices_superiores]
print("\nElementos superiores:")
print(elementos_superiores, '\n')

# np.trill_indices : obtiene los índices de los
# elementos inferiores de una matriz cuadrada
indices_inferiores = np.tril_indices(matriz.shape[0], k=-1)
elementos_inferiores = matriz[indices_inferiores]
print("Elementos inferiores:")
print(elementos_inferiores)

[[73 86 90 20]
 [96 55 15 48]
 [38 63 96 95]
 [13 87 32 96]] 

[73 55 96 96] 

k=1 [86 15 95]
k=2 [90 48]
k=3 [20]

k=-1 [96 63 32]
k=-2 [38 87]
k=-3 [13]

 [[ 0 86 90 20]
 [96  0 15 48]
 [38 63  0 95]
 [13 87 32  0]]

Elementos superiores:
[86 90 20 15 48 95] 

Elementos inferiores:
[96 38 63 13 87 32]


# Operaciones sobre arrays

## Operaciones lógicas

### Indexado booleano
El indexado booleano es una operación que permite conocer (a nivel de elemento) si un array cumple o no con una determinada condición.
Las condiciones pueden ser más complejas e incorporar operadores lógicos `|` (or) y `&` (and).

Si lo que nos interesa es obtener los índices del array que satisfacen una determinada condición, NumPy nos proporciona el método `where()`.

In [ ]:
valores = np.array([[60, 47, 34, 38],
[43, 63, 37, 68],
[58, 28, 31, 43],
[32, 65, 32, 96]])

print(valores > 50, '\n') # indexado booleano

print(valores[valores > 50], '\n') # uso de máscara

valores[valores > 50] = -1 # modificación de valores

print(valores, '\n')

# Operadores lógicos | y &
print((valores < 25) | (valores > 75), '\n')

print((valores > 25) & (valores < 75), '\n')

# Extracción de impares con la función where()
id_impar = np.where(valores % 2 != 0)
print(valores[id_impar])

[[ True False False False]
 [False  True False  True]
 [ True False False False]
 [False  True False  True]] 

[60 63 68 58 65 96] 

[[-1 47 34 38]
 [43 -1 37 -1]
 [-1 28 31 43]
 [32 -1 32 -1]] 

[[ True False False False]
 [False  True False  True]
 [ True False False False]
 [False  True False  True]] 

[[False  True  True  True]
 [ True False  True False]
 [False  True  True  True]
 [ True False  True False]] 

[-1 47 43 -1 37 -1 -1 31 43 -1 -1]


### Ejercicio
Partiendo de una matriz de 10 filas y 10 columnas con valores aleatorios enteros en el intervalo
[0, 100], realice las operaciones necesarias para obtener una matriz de las mismas dimensiones donde:
* Todos los elementos de la diagonal sean 50.
* Los elementos mayores que 50 tengan valor 100.
* Los elementos menores que 50 tengan valor 0.

In [ ]:
import numpy as np
matriz = np.random.randint(1, 100, size=(10, 10))
print(matriz, '\n')

# Modificamos los valores de la diagonal por 50
indices = np.diag_indices(matriz.shape[0])
matriz[indices] = 50
print(matriz, '\n')

# Elementos mayores a 50 con valor 100
matriz[matriz > 50] = 100
print(matriz, '\n')

# Elementos menores a 50 con valor 0
matriz[matriz < 50] = 0
print(matriz, '\n')

[[77 63  2 53 56 46 79 28 43 25]
 [97 67 77 68 68 71 78 14  8 84]
 [74 10 25 88 82 47 90 57 59 80]
 [78 53 57 33 39 50 37 37 81 45]
 [ 3 65 36 74 67  9 37 77 43 89]
 [30 69 39 82 90 11 55 91 20 93]
 [22 53 23 49 15 64 14  3 47 20]
 [61 70 94 76 46 19 55 19 71 58]
 [14 98 98 27 67 16 79 36 72 90]
 [35 13 74 69 99 27 96 69 19  9]] 

[[50 63  2 53 56 46 79 28 43 25]
 [97 50 77 68 68 71 78 14  8 84]
 [74 10 50 88 82 47 90 57 59 80]
 [78 53 57 50 39 50 37 37 81 45]
 [ 3 65 36 74 50  9 37 77 43 89]
 [30 69 39 82 90 50 55 91 20 93]
 [22 53 23 49 15 64 50  3 47 20]
 [61 70 94 76 46 19 55 50 71 58]
 [14 98 98 27 67 16 79 36 50 90]
 [35 13 74 69 99 27 96 69 19 50]] 

[[ 50 100   2 100 100  46 100  28  43  25]
 [100  50 100 100 100 100 100  14   8 100]
 [100  10  50 100 100  47 100 100 100 100]
 [100 100 100  50  39  50  37  37 100  45]
 [  3 100  36 100  50   9  37 100  43 100]
 [ 30 100  39 100 100  50 100 100  20 100]
 [ 22 100  23  49  15 100  50   3  47  20]
 [100 100 100 100  46  19 100  50

## Comparando arrays
Dados dos arrays podemos compararlos usando el operador `==` del mismo modo que con cualquier otro objeto en Python. La cuestión es que el resultado se evalúa a nivel de elemento.  
Si queremos comparar arrays en su totalidad, podemos hacer uso de la siguiente función `np.array_equal()`.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])

print(a == b)

# Si queremos comparar arrays en su totalidad, podemos hacer uso de la siguiente función:
print(np.array_equal(a, b))

[[ True  True]
 [ True  True]]
True


## Operaciones de conjunto
Al igual que existen operaciones sobre conjuntos en Python, también podemos llevarlas a cabo sobre arrays en NumPy.

In [ ]:
import numpy as np

x = np.array([ 9, 4, 11, 3, 14, 5, 13, 12, 7, 14])
y = np.array([17, 9, 19, 4, 18, 4, 7, 13, 11, 10])

# Unión
print(np.union1d(x, y))

# Intersección
print(np.intersect1d(x, y))

# Diferencia
print(np.setdiff1d(x, y))

[ 3  4  5  7  9 10 11 12 13 14 17 18 19]
[ 4  7  9 11 13]
[ 3  5 12 14]


## Ordenación de arrays
En términos generales, existen dos formas de ordenar cualquier estructura de datos, una que modifica «in-situ» los valores (destructiva) y otra que devuelve «nuevos» valores (no destructiva). En el caso de NumPy también es así.

In [ ]:
import numpy as np
# Ordenación array unidimensionales

valores = np.array([23, 24, 92, 88, 75, 68, 12, 91, 94, 24, 9, 21, 42, 3, 66])
print(valores)

# Operación no destructiva
print(np.sort(valores))

# Operación destructiva
valores.sort()
print(valores)

# Ordenación multidimensionales
matriz = np.array([[52, 23, 90, 46],
[61, 63, 74, 59],
[75, 5, 58, 70],
[21, 7, 80, 52]])

# No destructiva
print(np.sort(matriz, axis=1)) # Por columnas
print(np.sort(matriz, axis=0)) # Por filas

# Destructiva
matriz.sort(axis=1)
print(matriz)

matriz.sort(axis=0)
print(matriz)

[23 24 92 88 75 68 12 91 94 24  9 21 42  3 66]
[ 3  9 12 21 23 24 24 42 66 68 75 88 91 92 94]
[ 3  9 12 21 23 24 24 42 66 68 75 88 91 92 94]
[[23 46 52 90]
 [59 61 63 74]
 [ 5 58 70 75]
 [ 7 21 52 80]]
[[21  5 58 46]
 [52  7 74 52]
 [61 23 80 59]
 [75 63 90 70]]
[[23 46 52 90]
 [59 61 63 74]
 [ 5 58 70 75]
 [ 7 21 52 80]]
[[ 5 21 52 74]
 [ 7 46 52 75]
 [23 58 63 80]
 [59 61 70 90]]




# Ejemplos

In [ ]:
import numpy as np

# Creamos una matriz de ejemplo
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz)

# Calculamos la suma a lo largo del eje 0 (sumando las filas)
suma_filas = np.sum(matriz, axis=0)
print(f'Suma de filas: {suma_filas}')

# Calculamos la suma a lo largo del eje 1 (sumando las columnas)
suma_columnas = np.sum(matriz, axis=1)
print(f'Suma de columnas: {suma_columnas}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Suma de filas: [12 15 18]
Suma de columnas: [ 6 15 24]


## Contando valores
Otra de las herramientas útiles que proporciona NumPy es la posibilidad de contar el número de valores que existen en un array en base a ciertos criterios.

In [ ]:
aleatorios = np.random.randint(1, 11, size=100)
# print(aleatorios)

# Contando valores únicos
print(np.unique(aleatorios))

# Valores únicos (incluyendo frecuencias):
print(np.unique(aleatorios, return_counts=True))

# Valores distintos de cero:
print(np.count_nonzero(aleatorios))

# Valores distintos de cero (incluyendo condición):
print(np.count_nonzero(aleatorios > 5))

[ 1  2  3  4  5  6  7  8  9 10]
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), array([ 6, 11,  9,  9, 12, 13, 10, 10, 12,  8]))
100
53


## Operaciones aritméticas
Una de las grandes ventajas del uso de arrays numéricos en NumPy es la posibilidad de trabajar con ellos como si fueran objetos «simples» pero sacando partido de la aritmética vectorial. Esto redunda en una mayor eficiencia y rapidez de cómputo.

In [ ]:
import numpy as np
a = np.array([[21, 86, 45], [31, 36, 78], [31, 64, 70]])

b = np.array([[58, 67, 17], [99, 53, 9], [92, 42, 75]])

print(a + b, '\n')
print(a - b, '\n')
print(a * b, '\n')
print(a / b, '\n')
print(a // b, '\n')

[[ 79 153  62]
 [130  89  87]
 [123 106 145]] 

[[-37  19  28]
 [-68 -17  69]
 [-61  22  -5]] 

[[1218 5762  765]
 [3069 1908  702]
 [2852 2688 5250]] 

[[0.36206897 1.28358209 2.64705882]
 [0.31313131 0.67924528 8.66666667]
 [0.33695652 1.52380952 0.93333333]] 

[[0 1 2]
 [0 0 8]
 [0 1 0]] 



## Operaciones aritméticas con distintas dimensiones
Cuando operamos entre arrays con dimensiones diferentes, siempre y cuando se cumplan ciertas restricciones en tamaños de filas y/o columnas, lo que se produce es un «broadcasting» (o difusión) de los valores.

En el caso de que no coincidan dimensiones de filas y/o columnas, NumPy
no podrá ejecutar la operación y obtendremos un error: `ValueError: operands could not be broadcast together with shapes`

In [ ]:
import numpy as np
numeros = np.array([[9, 8, 1], [7, 6, 7]])

fila = np.array([[2, 3, 6]])
columna = np.array([[100], [1000]])

# Suma con array fila
print(numeros + fila, '\n')
print(numeros + columna, '\n')

[[11 11  7]
 [ 9  9 13]] 

[[ 109  108  101]
 [1007 1006 1007]] 



## Operaciones entre arrays y escalares
Al igual que ocurría en los casos anteriores, si operamos con un array y un escalar, éste último será difundido para abarcar el tamaño del array.

In [ ]:
import numpy as np
numeros = np.array([[9, 8, 1], [7, 6, 7]])

print(numeros + 10, '\n')
print(numeros - 10, '\n')
print(numeros * 10, '\n')
print(numeros / 10, '\n')
print(numeros // 10, '\n')

[[19 18 11]
 [17 16 17]] 

[[-1 -2 -9]
 [-3 -4 -3]] 

[[90 80 10]
 [70 60 70]] 

[[0.9 0.8 0.1]
 [0.7 0.6 0.7]] 

[[0 0 0]
 [0 0 0]] 



## Reduciendo el resultado
NumPy nos permite aplicar cualquier función sobre un array reduciendo el resultado por alguno de sus ejes. Esto abre una amplia gama de posibilidades.

In [ ]:
import numpy as np
valores = np.array([[8, 2, 7], [2, 0, 6], [6, 3, 4]])

print(np.sum(valores, axis=0)) # suma por columnas

print(np.sum(valores, axis=1)) # suma por filas

print(np.prod(valores, axis=0)) # producto por columnas

print(np.prod(valores, axis=1)) # producto por filas

[16  5 17]
[17  8 13]
[ 96   0 168]
[112   0  72]


## Funciones estadísticas
NumPy proporciona una gran cantidad de funciones estadísticas que pueden ser aplicadas sobre arrays.

## Máximos y mínimos
Una de las operaciones más comunes en el manejo de datos es encontrar máximos o
mínimos. Para ello, disponemos de las típicas funciones con las ventajas del uso de arrays multidimensionales

### Obtener los índices
Las funciones `argmax()` y `argmin()` son funciones utilizadas para encontrar los índices de los valores máximo y mínimo en un arreglo o secuencia, respectivamente.

Si hay múltiples valores ya sea máximos o mínimos, solo devuelve el índice del primer mínimo encontrado.

In [ ]:
import numpy as np

dist = np.array([[-6.79006504, -0.01579498, -0.29182173, 0.3298951 , -5.30598975],
[ 3.10720923, -4.09625791, -7.60624152, 2.3454259 , 9.23399023],
[-7.4394269 , -9.68427195, 3.04248586, -5.9843767 , 1.536578 ],
[ 3.33953286, -8.41584411, -9.530274 , -2.42827813, -7.34843663],
[ 7.1508544 , 5.51727548, -3.20216834, -5.00154367, -7.15715252]])

print(np.mean(dist))
print(np.std(dist))
print(np.median(dist))

# Max y Min
valores = np.array([[66, 54, 33, 15, 58],
[55, 46, 39, 16, 38],
[73, 75, 79, 25, 83],
[81, 30, 22, 32, 8],
[92, 25, 82, 10, 90]])

# Mínimos
print(np.min(valores), '\n')
print(np.min(valores, axis=0)) # Por filas
print(np.min(valores, axis=1)) # Por columnas

print(np.max(valores), '\n')
print(np.max(valores, axis=0))
print(np.max(valores, axis=1))

# Funciones argmax() y argmin()
print('\n',np.argmax(valores))
print(np.argmax(valores, axis=0))
print(np.argmax(valores, axis=1))

print('\n', np.argmin(valores))
print(np.argmin(valores, axis=0))
print(np.argmin(valores, axis=1))


-2.1877878728
5.393254993673597
-3.20216834
8 

[55 25 22 10  8]
[15 16 25  8 10]
92 

[92 75 82 32 90]
[66 55 83 81 92]

 20
[4 2 4 3 4]
[0 0 4 0 0]

 19
[1 4 3 4 3]
[3 3 3 4 3]


## Vectorizando funciones
Una de las ventajas de trabajar con arrays numéricos en NumPy es sacar provecho de la optimización que se produce a nivel de la propia estructura de datos.

In [2]:
import numpy as np
import timeit
# Veamos un ejemplo en el que queremos realizar el siguiente
# cálculo entre dos matrices 𝐴 y B

# Fun. definida
def custom(a, b):
    if a > b:
        return a + b
    elif a < b:
        return a - b
    else:
        return 0

A = np.random.randint(-100, 100, size=(3000, 3000))
B = np.random.randint(-100, 100, size=(3000, 3000))
result = np.zeros_like(A)

%%timeit
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        result[i, j] = customf(A[i, j], B[i, j])

UsageError: Line magic function `%%timeit` not found.


In [7]:
import timeit
import numpy as np

def customf(a, b):
    if a > b:
        return a + b
    elif a < b:
        return a - b
    else:
        return 0

# Paso 2: Definir la función a medir
def my_function(arg1, arg2):
    # Código de la función
    vectorizada = np.vectorize(customf)
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            result[i, j] = vectorizada(A[i, j], B[i, j])

A = np.random.randint(-100, 100, size=(10, 10))
B = np.random.randint(-100, 100, size=(10, 10))
result = np.zeros_like(A)

my_function(A, B)
print(result)

[[   0  -88  -26   95  -46  -33   -1  -55  116 -125]
 [ -60  -10  -73 -163  -35  -10  -37 -105    6   89]
 [-168 -140  -11 -114  -85  -27  -43  144  -20    4]
 [   0 -137   46  -46   20 -146 -146  -26 -101   19]
 [ -49  104  -82  -53   25  -51  -48  -17  -55 -137]
 [  -6    3  -18  122  -19   12 -157   24  -88    4]
 [  34  -39 -138  -67  -39   49  -84   57  -70  -96]
 [  65  -95  -78  -66   44   78  -54  -96  -74  -15]
 [-125  -54 -156 -107  178 -114  -24  -29  -12  -66]
 [ -98  -61 -102  107 -169  -60   41 -109  116  -72]]


## Ejercicio
1. Cree dos matrices cuadradas de 20x20 con valores aleatorios flotantes uniformes en el
intervalo [0, 1000)
2. Vectorice una función que devuelva la media (elemento a elemento) entre las dos
matrices.
3. Realice la misma operación que en 2) pero usando suma de matrices y división por
escalar.
4. Compute los tiempos de ejecución de 2) y 3)

---
#### Primera aproximación

In [47]:
import numpy as np
import timeit

# 1 - Matrices
a = np.random.uniform(0, 1000, size=(2, 2))
b = np.random.uniform(0, 1000, size=(2, 2))
resultado = np.zeros_like(a)
print(a, '\n')
print(b, '\n')

# 2  - Media
calcular_media = np.vectorize(lambda a, b: (a + b) / 2)

# 3 - Suma de matrices y división escalar
calcular_matriz = np.vectorize(lambda a, b: (a + b) / 10)

resultado_media = calcular_media(a, b)
resultado_matriz = calcular_matriz(a, b)

print(resultado_media, '\n')
print(resultado_matriz, '\n')

[[769.30627376 276.54996281]
 [ 45.42471518 638.4913786 ]] 

[[ 23.70953846 571.87239359]
 [881.75751347 932.87878794]] 

[[396.50790611 424.2111782 ]
 [463.59111432 785.68508327]] 

[[ 79.30158122  84.84223564]
 [ 92.71822286 157.13701665]] 



#### Resultado final

In [53]:
import numpy as np
import timeit

codigo_media = '''
import numpy as np

a = np.random.uniform(0, 1000, size=(20, 20))
b = np.random.uniform(0, 1000, size=(20, 20))
resultado = np.zeros_like(a)

calcular_media = np.vectorize(lambda a, b: (a + b) / 2)

resultado_media = calcular_media(a, b)
'''

codigo_suma = '''
import numpy as np

a = np.random.uniform(0, 1000, size=(20, 20))
b = np.random.uniform(0, 1000, size=(20, 20))
resultado = np.zeros_like(a)

calcular_matriz = np.vectorize(lambda a, b: (a + b) / 10)

resultado_matriz = calcular_matriz(a, b)
'''

timer_media = timeit.Timer(codigo_media)
timer_suma = timeit.Timer(codigo_suma)

execution_time_media = timer_media.timeit(number=1)
execution_time_suma = timer_suma.timeit(number=1)

print("Tiempo de ejecución media:", execution_time_media)
print("Tiempo de ejecución suma:", execution_time_suma)


Tiempo de ejecución media: 0.0004814889998669969
Tiempo de ejecución suma: 0.00029931700009910855


# Ejemplo

In [ ]:
# Resolver ecuaciones lineales

import numpy as np

a = np.array([[8, 10],
             [2, 5]])

b = np.array([80, 25])

print(np.linalg.solve(a, b))

c = np.array([[1, 2, 1],
 [2, 4, 2], # Note that this row 2 * the first row
 [1, 0, 1]])
d = np.array([4,8,5])
x, residuals, rank, s = np.linalg.lstsq(c, d)
print(x)

[7.5 2. ]
[ 2.5 -0.5  2.5]


<ipython-input-9-a510201570c4>:17: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, residuals, rank, s = np.linalg.lstsq(c, d)
